name: Check PR base branch
on:
  pull_request:
    branches:
      - main

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if PR base is not 'dev'
      run: |
        if [[ "${{ github.base_ref }}" != "dev" ]]; then
          echo "Error: Pull requests must be based on 'dev' branch"
          exit 1
        fi