name: Client - CI with pull request
on:
  push:
    branches:
      - Server-Developpement
    paths:
      - client/**
  pull_request:
    branches:
      - Server-Developpement
    paths:
      - client/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Run tests
        run: |
          cd client
          yarn test
